### ISSUE TITLE
64-bit INTEGER

### ISSUE THREAD

**Issue by sts-q** [ericscharff/oberon-compiler#1] opened 2024-09-25 20:19 UTC
The compiler uses 32-bit integer for all Oberon INTEGER.
In order to use 64-bit integer i go like this, which makes all INTEGER 64-bit:

https://github.com/sts-q/oberon-compiler/commit/284b115abc8ebe8ea3cd8d929d650dfd3fd376d7?diff=unified

Seems to work for my modules, so far.

Regards!

**Comment by ericscharff** [comment] 2024-09-26 01:54
Thanks for the bug report and for the fix!

I decided not to use your pull request as-is, because there are two mechanisms in the compiler for overriding types. You could use preprocessor defines, like `-DOBERON_REAL=double` already. So, I've made two code changes.

1. Make it possible to also override `OBERON_INTEGER`
2. Add command line flags to the compiler to optionally use int64 (flag `-use_int64`)

I've not yet set this to the default for two reasons. First, it's somewhat nice that the 32 bit C code matches the 32 bit RISC code. Second, and more importantly, some of my regression tests fail with an int64 type, so I'd like to fix that before making it the C default.

Hopefully this fix will work for you, And thanks again! I'm happy to consider other PRs in the future.

**Comment by ericscharff** [comment] 2024-09-26 01:57
Fixed in commit 30b408e

**Closed as completed** 2024-09-26 01:57 UTC

**Comment by sts-q** [comment] 2024-09-26 06:56
Thank you Eric,

you changes work perfect for me.

Regards!
